FROM ubuntu:latest

RUN apt update
RUN apt install sudo -y
RUN sudo apt update -y

FROM python:3



COPY requirements.txt requirements.txt
COPY Node.py Node.py 
COPY config.ini config.ini 
RUN pip3 install -r requirements.txt
CMD [ "python", "./Node.py" ]